install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -40,7 +40,7 @@ clear
 # Preparar ambiente del VPS
 echo -e "\033[1;32m 1/5 Preparando VPS... \033[0m"
 sudo apt-get -yqqq update >/dev/null 2>&1
-sudo apt-get -yqqqq install sudo curl nano zip htop unzip wget >/dev/null 2>&1
+sudo apt-get -yqqq install sudo curl nano zip htop unzip wget >/dev/null 2>&1
 sudo apt-get -yqqq clean >/dev/null 2>&1
 sudo apt-get -yqqq autoclean >/dev/null 2>&1
 sudo apt -yqqq autoremove --purge snapd >/dev/null 2>&1
@@ -50,7 +50,8 @@ clear
 
 # Instalar Docker
 echo -e "\033[1;32m 2/5 Instalando Docker... \033[0m"
-sudo curl -fsSL https://get.docker.com -o get-docker.sh; sudo sh get-docker.sh >/dev/null 2>&1
+sudo curl -fsSL https://get.docker.com -o get-docker.sh
+sudo sh get-docker.sh >/dev/null 2>&1
 sudo service docker start >/dev/null 2>&1
 sudo systemctl start docker >/dev/null 2>&1
 clear
@@ -89,7 +90,7 @@ services:
       - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
       - "traefik.http.routers.redirs.entrypoints=web"
       - "traefik.http.routers.redirs.middlewares=redirect-to-https"
-      - "traefik.http.routers.api.rule=Host(`traefik.$SUBDOMINIO`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))" # Asegúrate de tener un subdominio para Traefik Dashboard
+      - "traefik.http.routers.api.rule=Host(`traefik.$SUBDOMINIO`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
       - "traefik.http.routers.api.service=api@internal"
       - "traefik.http.routers.api.entrypoints=websecure"
       - "traefik.http.routers.api.tls.certresolver=myresolver"
@@ -131,10 +132,10 @@ services:
       - "traefik.http.services.portainer.loadbalancer.server.port=9000"
     networks:
       - traefik_network
-      
+
 volumes:
   portainer_data:
-    
+
 networks:
   traefik_network:
     external: true
@@ -144,9 +145,23 @@ cd /opt/portainer
 sudo docker-compose up -d
 clear
 
+# Verificar la creación de la red traefik_network
+echo -e "\033[1;32m Verificando la creación de la red traefik_network... \033[0m"
+if ! sudo docker network inspect traefik_network >/dev/null 2>&1; then
+  echo -e "\033[1;31m Error: La red traefik_network no se creó correctamente. \033[0m"
+  exit 1
+fi
+
+# Verificar la creación del contenedor de Portainer
+echo -e "\033[1;32m Verificando la creación del contenedor de Portainer... \033[0m"
+if ! sudo docker ps -a --format '{{.Names}}' | grep -q portainer; then
+  echo -e "\033[1;31m Error: El contenedor de Portainer no se creó correctamente. \033[0m"
+  exit 1
+fi
+
 # Esperar que se active portainer
 echo -e "\033[1;32m 5/5 Finalizando instalación... \033[0m"
-sleep 15
+sleep 30
 clear
 
 # Mostrar mensaje final
@@ -155,5 +170,5 @@ echo -e "\033[1;32m|           La preparación está OK!          |\033[0m"
 echo -e "\033[1;31m==============================================\033[0m\n"
 echo -e "\033[1;33m Accede a Portainer desde: \033[0m\e[32mhttps://$SUBDOMINIO\e[0m\n"
 echo -e "\033[1;33m Accede a Traefik Dashboard desde: \033[0m\e[32mhttps://traefik.$SUBDOMINIO\e[0m\n"
-echo -e "\033[1;31m Usuario: test \033[0m"
-echo -e "\033[1;31m Contraseña: test \033[0m"
+echo -e "\033[1;31m Usuario: test \033[0m" # Recuerda cambiar esta contraseña
+echo -e "\033[1;31m Contraseña: test \033[0m" # Recuerda cambiar esta contraseña
